### PR TITLE
Added tests for the distribution of nodes and edges in tree sequences…

### PR DESCRIPTION
**Pull request by General-Solution**
… with or without record_unary=True.

The tests are grouped under the class UnaryRecordTest and have a similar format to ArgRecordTest. The expected results are that the distribution of nodes and edges is the same after simplifying unary nodes as it is when simulating without record_unary enabled.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks very nice! @GertjanBisschop would you mind taking a look please?

**Comment by GertjanBisschop** [comment]
Nice, thanks @General-Solution. LGTM. Small note, currently, multiple merger events do not result in unary nodes, so the tests for the Beta - and Dirac coalescent are probably a bit overkill.

**Review by jeromekelleher — APPROVED** [review]
LGTM!

**Comment by jeromekelleher** [comment]
Looks like you just need to run the code through Black - the [pre-commit](https://tskit.dev/tskit/docs/stable/development.html#sec-development-workflow-pre-commit) docs should help with this

**Comment by jeromekelleher** [comment]
Excellent! Now, we just need to [squash the commits](https://popsim-consortium.github.io/stdpopsim-docs/stable/development.html#rebasing) and we're ready to go

**Comment by jeromekelleher** [comment]
@General-Solution - I just spotted that you're using the main branch of your fork for this, which is generally complicates things. Much better to use a feature branch like we recommend in the [developer docs](https://tskit.dev/tskit/docs/stable/development.html#workflow)

**Pull request merged**
