### PR TITLE
Store flake8 config and update docs

### PR DESCRIPTION
**Pull request by benjeffery**
I found the method in the docs wasn't running `flake8` and so wasn't preventing commits. The `flake8` docs suggest this new method. I also added a `.flake8` file to store our specific standards.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Very nice, thanks @benjeffery.

The ``large_example.py`` file is ancient, let's just delete it. Can you rebase as well please? (Not strictly necessary to rebase here, but it's nice to keep a linear history where possible IMO)

**Comment by benjeffery** [comment]
I've removed the old file, and also changed the CI linting to use the new config. I also rebased. An option is to get github to do this when you merge PRs!: https://help.github.com/en/github/administering-a-repository/configuring-commit-rebasing-for-pull-requests)

**Comment by benjeffery** [comment]
Looks like the CI has failed for an unrelated reason (I think!).

**Comment by jeromekelleher** [comment]
> Looks like the CI has failed for an unrelated reason (I think!).

Not sure what happened there, have restarted Travis build. It's definitely unrelated anyway though.

> An option is to get github to do this when you merge PRs!: https://help.github.com/en/github/administering-a-repository/configuring-commit-rebasing-for-pull-requests)

I tried the "rebase and merge" option before and it didn't seem like quite the same thing, but let's talk about this when we meet. This is just the sort of process thing we want to make as simple as possible.

**Comment by jeromekelleher** [comment]
Travis is happy, the world is good.

**Pull request merged**
