### PR TITLE
Disable doc upload

### PR DESCRIPTION
**Pull request by benjeffery**

### CODE REVIEW

**Comment by AdminBot-tskit** [comment]
📖 Docs for this PR can be previewed [here](https://tskit-dev.github.io/msprime-docs/PR-1321/)

**Comment by jeromekelleher** [comment]
Looks like this also pulled in some changes to the tskit submodule?

**Comment by benjeffery** [comment]
Gah, was in haste. Will fix.

**Comment by jeromekelleher** [comment]
No worries - it's annoyingly easy to do this with submodules! #1324 should help.

**Pull request merged**
