### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by grahamgower**
I used pyspelling and proselint.

---

I admit, some of this is of dubious value.

pyspelling config file:
```yaml
# pip install pyspelling resplendent

matrix:
- name: py-comment
  aspell: &aspell
    lang: en
    d: en_GB
  dictionary: &dictionary
    wordlists:
    - pyspelling-wordlist.txt
    output: build/wordlist.dict
  sources: &python-sources
  - msprime/**/*.py
  #- tests/**/*.py
  pipeline:
  - pyspelling.filters.python:
      comments: true
      group_comments: true
      docstrings: false
      strings: false
  - pyspelling.filters.url:

- name: py-docstring
  aspell: *aspell
  dictionary: *dictionary
  sources: *python-sources
  pipeline:
  - pyspelling.filters.python:
      comments: false
  - resplendent.filters.restructuredtext:
  - pyspelling.filters.html: &html-filter
      comments: false
      ignores:
        - code
        - pre
        - tt
        # Field list names, like :rtype: or :param int mynum:.
        - .field-name
        # Sphinx things docutils ignores, like :class:`foo` or :func:`bar`.
        - .problematic
  - pyspelling.filters.url:

- name: py-string
  aspell: *aspell
  dictionary: *dictionary
  sources: *python-sources
  pipeline:
  - pyspelling.filters.python:
      strings: true
      comments: false
      docstrings: false
  - pyspelling.filters.url:

- name: c-string
  aspell: *aspell
  dictionary: *dictionary
  sources:
  # Just target strings that propagate to error messages.
  - msprime/_msprimemodule.c
  - lib/util.c
  #- lib/**/*.{c,h} 
  pipeline:
  - pyspelling.filters.cpp:
      block_comments: false
      line_comments: false
      strings: true

- name: markdown
  aspell: *aspell
  dictionary: *dictionary
  sources:
  - README.md
  - docs/*.md
  pipeline:
  - pyspelling.filters.context:
      context_visible_first: true
      # Ignore jupytext/YAML header.
      delimiters:
      - open: '(?s)^---$'
        close: '^---$'
      # Ignore fenced content (fences can have 3 or more back ticks)
      # ```
      # content
      # ```
      - open: '(?s)^(?P<open> *`{3,})'
        close: '^(?P=open)$'
      # Ignore text between inline back ticks
      - open: '(?P<open>`+)'
        close: '(?P=open)'
      - open: '\{func\}'
        close: '(?=.)'
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.admonition
      - markdown.extensions.def_list
  - pyspelling.filters.html: *html-filter
  - pyspelling.filters.url:

```

Ignore wordlist (would need a lot more additions to be useful in an automated setting)
```
accessors
API
APIs
ARG
allelic
benchmarking
BLOSUM
breakpoint
browsable
canonicalise
centiMorgan
centiMorgans
changelog
CLI
coalescences
conda
contig
contigs
deme
deme's
demes
demographies
deprecations
dest
deserialise
discretisation
discoal
docstring
docstrings
DTWF
durations
encodable
errored
Ewens
Felsenstein
Fenwick
genomic
genotype
genotypes
github
globals
GSL
Gutenkunst
gzipped
haplotype
haplotypes
HDF
heterozygote
heterozygotes
highlevel
HKY
homonymous
homozygous
homozygote
homozygotes
hotspot
hotspots
interpretable
iterable
iteratively
JC
JSON
Jupyter
JupyterBook
Jukes
kastore
Kelleher
losslessly
lowlevel
macOS
Markovian
McVean
MERCHANTABILITY
msp
mspms
msprime
msprime's
miniconda
misspecification
monoploid
MyST
namespace
NaN
newick
noreorder
nonequilibrium
nonnegative
NOQA
noqa
nucleotides
numpy
OSX
parameterisation
parameterisations
parsers
piecewise
pipelined
ploidy
podman
polyploid
POSIX
posix
postorder
pragma
pseudorandom
PyPI
pyslim
pytest
quickstart
reentrant
recombinations
reimplementation
rescaling
rescaled
repo
schemas
SLiM
SMC
skewness
StarBEAST
stderr
stdin
stdout
stdpopsim
struct
subclasses
subcommand
subcommands
submodules
subpopulation
subpopulations
subprocesses
superclass
superset
SVG
toolchain
topologies
traceback
transversion
transversions
TreeAnnotator
triploid
tskit
tszip
TODO
ultrametric
uncoalesced
unnormalised
valgrind
VCF
whitespace
YAML
```

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
Looks good to me! I'm not convinced about this pipeline's aversion to the phrase "a number of", but :shrug: 

How much work was this to set up, and use?

**Comment by grahamgower** [comment]
> Looks good to me! I'm not convinced about this pipeline's aversion to the phrase "a number of", but 

[`proselint`](http://proselint.com/) complained about "a number of different", and a couple of other things that it thought were redundant language. I didn't bother changing much from proselint --- lot's of noise because it doesn't understand MyST markdown extensions.

> How much work was this to set up, and use?

[`pyspelling`](https://facelessuser.github.io/pyspelling/) isn't too hard to write a config file for, although it could use more example configurations in the docs. Figuring out the correct html filters to apply under `pyspelling.filters.html` needed some messing around ([`replendent`](https://github.com/resplendent-dev/resplendent) converts the python docstrings in rst format into html using `docutils`, which doesn't exactly match sphinx display). Probably there are some improvements that could be made to the config with more time investment.

With this config, and the wordlist I posted, there are still *a lot* of false positives (lots of class names and variable names like 'num' leaking through). I assume these would be better dealt with by figuring out how to filter things better, rather than adding to the wordlist.

Overally, I'd say run it once every year or two. Or spend more time figuring out how to make it more useful so you can run it every release (and on more repositories).

**Comment by jeromekelleher** [comment]
Great, thanks @grahamgower.

It sounds like the this setup would be best suited to a separate repo in tskit-dev, which would allow us to manually run this stuff every now and again on different repos, without duplicating effort?

**Comment by grahamgower** [comment]
> It sounds like the this setup would be best suited to a separate repo in tskit-dev, which would allow us to manually run this stuff every now and again on different repos, without duplicating effort?

Yeah, that could work. Although there probably needs to be a small amount of project-specific configuration, if only to specify file paths.

**Pull request merged**
