### PR TITLE
Fix GC left process

### PR DESCRIPTION
**Pull request by jeromekelleher**
Reverts to the old way of doing things so that we're at least simulating the correct distribution.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
TODO: figure out what bits are redundant now and remove them.

**Comment by fbaumdicker** [comment]
This looks fine. If the tests still pass this should work correctly. However, it might be possible to quickly fix the new gc_left free simulation method as outlined here https://github.com/tskit-dev/msprime/issues/1161#issuecomment-689764259

**Comment by jeromekelleher** [comment]
> This looks fine. If the tests still pass this should work correctly. However, it might be possible to quickly fix the new gc_left free simulation method as outlined here #1161 (comment)

Thanks @fbaumdicker - I'll try out your idea to see if it works (easy enough to get rid of gc_left again if we don't want it). I'll merge this first though, in the interest of keeping the simulations correct in master.

**Comment by jeromekelleher** [comment]
So, I won't remove the redundant bits of the gc_event yet, so we can experiment with the single-process version.

**Pull request merged**
