### PR TITLE
Multiple merger timescale docs

### PR DESCRIPTION
**Pull request by JereKoskela**
Ping @TPPSellinger & @jeromekelleher - slight clarification of the Beta-coalescent timescale when alpha is close to 2 as discussed.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
@TPPSellinger, I'll wait for your input here before merging.

**Comment by TPPSellinger** [comment]
Sorry for the delay, I think the note of @JereKoskela is perfectly clear!

**Comment by JereKoskela** [comment]
@jeromekelleher, do you know what's going on with this pull request? It shows Travis CI as "in progress" after several days, but the corresponding Details link says it passed after 6 minutes.

**Comment by benjeffery** [comment]
I've restarted travis - the build completed successfully but travis failed to report back. Many people have been having this issue on and off for a while.

**Pull request merged**
