### PR TITLE
More doc fixing

### PR DESCRIPTION
**Pull request by petrelharp**
Another minor doc bug found by @jgallowa07 - but I won't merge this yet, will wait to see if there's more

### CODE REVIEW

**Comment by jgallowa07** [comment]
Grammar suggestion: At the very end of the first paragraph, of `Variable recombination rates` in `API Documentation` say "(Although it does not get used)" rather than "(although it does not used)"

**Comment by jgallowa07** [comment]
In which direction of time does a positive `growth_rate` grow the population?

**Comment by jgallowa07** [comment]
Grammar suggestion: In API -> Simulating mutations -> class msprime.InfiniteSites(alphabet=0)
first paragraph "which has a floating-point position chose uniformly along the sequence." should be "which has a floating-point position **chosen** uniformly along the sequence."

**Comment by jgallowa07** [comment]
In API -> Using simulation results -> class msprime.TreeSequence -> edges(): Pretty trivial, but aren't you also guerenteed that `left` < `right` ... ?

**Comment by jgallowa07** [comment]
In API -> Using simulation results -> class msprime.TreeSequence: `num_sites` and `num_provenances` should probably have hyperlinks to sites and provenances, respectively

**Comment by jgallowa07** [comment]
Possible format suggestion; Maybe the `Table Collection Class` could come before the singular `Tables Class` in the API Documentation. This is mainly because Table Collection class conceptually encapsulates the singular tables just as the Tree Sequence class encapsulates the Table Collection class.

**Comment by jgallowa07** [comment]
Grammar suggestion: In Tree sequence interchange first sentence "The correlated genealogical trees that describe the shared ancestry of set of samples are stored concisely in msprime as a collection of easy-to-understand tables. " could instead be worded "The correlated genealogical trees that describe the shared ancestry **from a** set of samples are stored concisely in msprime as a collection of easy-to-understand tables. "

**Comment by jgallowa07** [comment]
In Tree Sequence Interchange -> Data Model -> tree, It might be good to remind the reader that a tree is how a set of samples are related **At some interval along the genome between two breakpoints**

**Comment by jgallowa07** [comment]
The reader may become slightly confused about whether the `derived state` in the `mutation table` ever becomes the `ancestral state` in the `site table` after fixation. Might be worth a small explanantion/discussion about the nature of simplify and Ancestral vs. Derived?

**Comment by jgallowa07** [comment]
Grammar suggestion: In Tree Sequence Interchange -> Data Model -> mutation, last sentence, "Its" instead of "It's"

**Comment by jgallowa07** [comment]
In Tree Sequence Interchange -> Nodes, Genomes, or Individuals you state "Since each monoploid copy of the genome is inherited separately, each diploid individual lies at the end of two distinct lineages, and so will be represented by two places in any genealogical tree." maybe "Since each monoploid copy of the genome is inherited separately, each diploid individual lies at the end of two distinct lineages **and will be** represented by two places in any genealogical tree." instead?

**Comment by jeromekelleher** [comment]
Can we update this and get it ready for merging please? I'd like to start getting stuff in place for 0.6.1 soon.

**Comment by petrelharp** [comment]
@jeromekelleher I'm changing 'deme' to 'subpopulation' throughout. If you complain, I'll change it back.

**Comment by petrelharp** [comment]
Suggestions I haven't done:

> Inline code example change: In classmethod uniform_map description you have >>> recomb_map = RecombinationMap.uniform_map(m, rate, num_loci=m) but it should be >>> recomb_map = msprime.RecombinationMap.uniform_map(m, rate, num_loci=m)

I think this is OK; assume the user has done `from msprime import *` for brevity in the docs.

> and, what is uniform_map(length, rate, num_loci=None) class method even used for if you can simply provide length and recombination_rate parameters

To specify a particular `num_loci`!

> In API -> Using simulation results -> class msprime.TreeSequence -> edges(): Pretty trivial, but aren't you also guerenteed that left < right ... ?

True, but that sentence is talking about guaranteed aspects of the *order* returned, not aspects of each edge itself.

> Possible format suggestion; Maybe the Table Collection Class could come before the singular Tables Class in the API Documentation. This is mainly because Table Collection class conceptually encapsulates the singular tables just as the Tree Sequence class encapsulates the Table Collection class.

Not sure what you mean here -- it's called TableCollection in the code; it should probably be called this in the docs?

> Grammar suggestion: In Tree sequence interchange first sentence "The correlated genealogical trees that describe the shared ancestry of set of samples are stored concisely in msprime as a collection of easy-to-understand tables. " could instead be worded "The correlated genealogical trees that describe the shared ancestry **from a** set of samples are stored concisely in msprime as a collection of easy-to-understand tables. "

I think "of a" is better than "from a", but I did change it to be "of a set" (instead of "of set").

> The reader may become slightly confused about whether the derived state in the mutation table ever becomes the ancestral state in the site table after fixation. Might be worth a small explanantion/discussion about the nature of simplify and Ancestral vs. Derived?

Good suggestion, but I haven't done it.

**Comment by petrelharp** [comment]
Squashed this down (I think).

**Comment by petrelharp** [comment]
Fixed.

**Comment by jeromekelleher** [comment]
Excellent, thanks. Merging.

**Pull request merged**
