### PR TITLE
Update pre-commit

### PR DESCRIPTION
**Pull request by benjeffery**

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM

I suspect the test failure is due to an update in pytest. Probably simplest to pin to an older version for the moment and register an issue.

**Comment by benjeffery** [comment]
> I suspect the test failure is due to an update in pytest. Probably simplest to pin to an older version for the moment and register an issue.

`pytest` is already pinned for CI on this repo, so I don't understand why these failures are happening. I can't recreate it locally.

**Comment by benjeffery** [comment]
I've managed to re-create this, it only happens in the latest patch version of Python 3.9. Fix on the way.

**Comment by jeromekelleher** [comment]
@mergifyio rebase

**Pull request merged**
