### PR TITLE
Small update to error message for MSP_ERR_TIME_TRAVEL

### PR DESCRIPTION
**Pull request by gtsambos**
Just a small edit to reflect that this error can also be caused by poor specification of census events

### CODE REVIEW

**Comment by gtsambos** [comment]
i'm a bit confused; this is passing the pre-commits on my local machine

**Comment by gtsambos** [comment]
don't have time to fix now but will look again later

**Comment by gtsambos** [comment]
Seems like you need a very specific version of ``clang-format`` to run that part of the pre-commit (the current version is 14.x)

> clang-format-6.0 not found, skipping this check

**Review by jeromekelleher — APPROVED** [review]
LGTM, thanks!

**Comment by jeromekelleher** [comment]
> Seems like you need a very specific version of clang-format to run that part of the pre-commit (the current version is 14.x)

This is a long running saga - don't ask!

I think you just have a trailing space on the end of one of the lines. Most editors can be configured to delete this.

**Pull request merged**
