### PR TITLE
Update pre-commit deps

### PR DESCRIPTION
**Pull request by benjeffery**
Same deal as https://github.com/tskit-dev/tskit/pull/856

### CODE REVIEW

**Comment by jeromekelleher** [comment]
LGTM. If there's no manual stuff in here, would you mind holding off on this one until #1190 lands? It's brewing into a fairly big diff, and I can't be bothered fixing the merge mess.

**Comment by benjeffery** [comment]
Yep, makes sense!

**Comment by jeromekelleher** [comment]
Can we replay this one please @benjeffery? I think this is a good time to get this one in.

**Comment by benjeffery** [comment]
@jeromekelleher Rebased!

**Review by jeromekelleher — APPROVED** [review]
LGTM!

**Pull request merged**
