### PR TITLE
avl syntax fixes

### PR DESCRIPTION
**Pull request by petrelharp**
Fixes thanks to @bhaller that I think have been discussed already with @jeromekelleher.

### CODE REVIEW

**Comment by petrelharp** [comment]
Also a minor fix in `trees.h` that caused errors if it was included more than once.

**Comment by jeromekelleher** [comment]
Looks good, thanks @petrelharp. Since this is someone else's code that we're modifying, I feel like we should record this fact somewhere in the header. Just the date and something like "Minor modifications to remove compiler warnings"?

This file won't be part of ``tskit`` BTW, so technically we don't really need this change if we're not worried about these compiler warnings in tskit-less msprime.

**Comment by bhaller** [comment]
The warnings that remain on my side are all to do with unused parameters (in tree_sequence.c, tables.c, and newick.c).  I saw that you defined KAS_UNUSED() in kastore.h, and I've been wondering whether it would be helpful for me to define essentially the same thing in tskit somewhere and add it where needed to get rid of those warnings.  Would that go in util.h?  I see that everything there still uses an "MSP_" naming convention; do you intend to rename stuff to TSK_ or some such?  Anyway, if you give me a bit of guidance I'm happy to push a fix for the remaining warnings that @petrelharp can then add to this pull request...

**Comment by jeromekelleher** [comment]
> The warnings that remain on my side are all to do with unused parameters (in tree_sequence.c, tables.c, and newick.c). I saw that you defined KAS_UNUSED() in kastore.h, and I've been wondering whether it would be helpful for me to define essentially the same thing in tskit somewhere and add it where needed to get rid of those warnings. Would that go in util.h? I see that everything there still uses an "MSP_" naming convention; do you intend to rename stuff to TSK_ or some such? Anyway, if you give me a bit of guidance I'm happy to push a fix for the remaining warnings that @petrelharp can then add to this pull request...

Sure, go for it! Yes, we'll change all the "MSP_" prefixes to "TSK_" when tskit finally gets split out (but lets keep them as MSP_ for now, for simplicity). ``util.h`` is a good place to put this.

**Comment by bhaller** [comment]
So if you've got a moment to explain, what does `#define MSP_UNUSED(x) MSP_UNUSED_ ## x __attribute__((__unused__))` actually do?  :->

**Comment by jeromekelleher** [comment]
The short answer is "it does what we want it to do", the longer answer is "I don't really know the details, I just copied it from somewhere when I googled how to do this sort of stuff"!

The idea of having a macro rather than just putting in the ``__attribute__((__unused__)`` values though is so that it can be used on compilers that don't support this sort of syntax (i.e., MSVC).

**Comment by bhaller** [comment]
> The short answer is "it does what we want it to do", the longer answer is "I don't really know the details, I just copied it from somewhere when I googled how to do this sort of stuff"!

lol.  The mysteries of the C preprocessor.

> The idea of having a macro rather than just putting in the __attribute__((__unused__) values though is so that it can be used on compilers that don't support this sort of syntax (i.e., MSVC).

Yep, that part I get.  :->

**Comment by petrelharp** [comment]
OK. I merged those WARN UNUSEDs in. Hopefully this doesn't make merging in `individual_tables` difficult.

**Comment by jeromekelleher** [comment]
Looks good, thanks. I'll merge one CI is done. Should be easy to rebase #472 on the result.

**Pull request merged**
