### PR TITLE
Update verification.py

### PR DESCRIPTION
**Pull request by TPPSellinger**
Adds SFS checks for ploidy 1 and 2.

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM, thanks @TPPSellinger!

Pinging @JereKoskela for a quick look over.

**Review by JereKoskela — APPROVED** [review]
Everything looks fine to me, thanks @TPPSellinger!

**Comment by JereKoskela** [comment]
It looks like something went wrong with the automerge @jeromekelleher. Any idea how to fix it?

**Comment by TPPSellinger** [comment]
I can redo the PR if necessary.

**Comment by jeromekelleher** [comment]
I'm not sure, looks like the rebase needed to bring the branch up to date failed. Can you try a rebase and force-push please @TPPSellinger?

**Comment by benjeffery** [comment]
@mergifyio refresh

**Comment by benjeffery** [comment]
@mergifyio rebase

**Comment by TPPSellinger** [comment]
Unfortunately rebasing might have to wait tomorrow morning. But I could create a new PR with the exact same code through the git gui right now if this would solve the problem quickly ?

**Comment by benjeffery** [comment]
@mergifyio rebase

**Comment by benjeffery** [comment]
@TPPSellinger I've fixed the issue this should now merge. The bot didn't have the right permissions.

**Comment by TPPSellinger** [comment]
Thank  you very much @benjeffery   !

**Pull request merged**
