### PR TITLE
Upgrade actions and use numpy2

### PR DESCRIPTION
**Pull request by benjeffery**

### CODE REVIEW

**Comment by benjeffery** [comment]
We need an arm64 kastore conda package - I'm not sure why there isn't one as we have them for tskit. Will investigate.

**Comment by jeromekelleher** [comment]
Ah, it's something you need to explicitly enable. Look back through tskit-feedstock prs

**Comment by jeromekelleher** [comment]
Any idea why these doc link references are failing now?

**Comment by benjeffery** [comment]
Really weird error from the docs not finding a cross-link. I've decoded and checked the `objects.inv` and the cross-link is there.

**Comment by jeromekelleher** [comment]
Let's just set the docs build to not error on warning for now, log an issue and get the rest shipped out.

**Review by jeromekelleher — APPROVED** [review]

**Comment by benjeffery** [comment]
Running wheel build tests then will merge.

**Comment by benjeffery** [comment]
Seems I need to follow https://github.com/matthew-brett/delocate?tab=readme-ov-file#making-dual-architecture-binaries to get the wheels for OSX

**Pull request merged**
