### PR TITLE
Workflow updates

### PR DESCRIPTION
**Pull request by benjeffery**
Switch to using new dependabot, which has worked well over at tskit.

Also update pre-commit, which has some opinions on typing specifications, and caught two missing `asserts`.

### CODE REVIEW

**Comment by benjeffery** [comment]
Seems the docs don't like the new style, will revert.

**Comment by grahamgower** [comment]
Pipes for union types don't work until Python 3.10, right? https://www.python.org/dev/peps/pep-0604/

**Comment by benjeffery** [comment]
> Pipes for union types don't work until Python 3.10, right? https://www.python.org/dev/peps/pep-0604/

Yes, I'm not sure why pyupgrade is putting them in considering we specify 3.7.

**Comment by benjeffery** [comment]
@grahamgower msprime does `from __future__ import annotations` which enables this syntax.

**Comment by benjeffery** [comment]
All fixed up, letting `jupyter-book` choose its own `sphinx` version fixed this.

**Review by jeromekelleher — APPROVED** [review]
Looks great, thanks @benjeffery! The pipe notation for typing is really nice, excellent we can use that.

**Pull request merged**
