### PR TITLE
Add pre-commit and black

### PR DESCRIPTION
**Pull request by benjeffery**
Starting to bring over the checks from tskit. This adds black, pre-commit and the github action. No rush to merge as can be easily rebased.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Nice. Looks like we need pre-commit in requirements.txt

**Comment by jeromekelleher** [comment]
Nice, thanks @benjeffery. Let's try and get the PR queue flushed first and then get this landed.

**Comment by jeromekelleher** [comment]
Let's do this now! I can't live without Black any more!!!

**Comment by benjeffery** [comment]
I feel your pain! Will rebase and get it in order tonight, and queue up PRs for the other goodies.

**Comment by benjeffery** [comment]
@jeromekelleher rebased and re-blacked.

**Comment by jeromekelleher** [comment]
MERGING!!! I've never been happier to merge a PR - black is life changing! Thanks for setting this up @benjeffery!

**Comment by benjeffery** [comment]
@jeromekelleher I didn't have time last night to do changes to the docs mentioning pre-commit etc.

**Comment by jeromekelleher** [comment]
I think we might start linking to the tskit dev docs here soon to reduce duplication. So minimal updates just to say we're doing this stuff for now is fine.

**Pull request merged**
