### PR TITLE
Add bugbear to pre-commit

### PR DESCRIPTION
**Pull request by benjeffery**
Adds bugbear and builtins checks to pre-commit. Note that this PR is stacked onto #973 as it requires flake8. To see the changes look at commit: https://github.com/tskit-dev/msprime/commit/a99168dfe67edaddcfb1b940824687716368aeac

This needs a proper check as there are meaningful code changes as bugbear found loops where variables were not used. In a couple of cases these are genuine errors I think.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Let's push this back until next week also.

**Comment by benjeffery** [comment]
@jeromekelleher rebased. I've made changes here to tests that I'd like double checked! Thanks!

**Comment by benjeffery** [comment]
Hmm, CI pre-commit is failing, local isn't.

**Comment by benjeffery** [comment]
Our github action runs pre-commit on python 3.8. Locally I run 3.6. https://www.python.org/dev/peps/pep-0553/ bought in `breakpoint` as a keyword in 3.7 so 3.8 fails. Fixed!

**Comment by jeromekelleher** [comment]
Changes all look sensible, let's get them queued up after #966.

**Pull request merged**
