### PR TITLE
Multiple merger docs + timescale

### PR DESCRIPTION
**Pull request by JereKoskela**
Docs for haploid multiple mergers ready for your perusal @jeromekelleher. I also found one niggling detail to fix in the timescale of the haploid Beta-coalescent.

I haven't provided any explanation of the interaction between the sample_size and ploidy arguments here, assuming that that would get covered somewhere more central. Happy to add more detail if you think it worth repeating though.

### CODE REVIEW

**Comment by JereKoskela** [comment]
Ok, it looks like I've somehow broken the entire python testing pipeline, but I can't see where I've touched anything that would explain how. I'll keep digging, but suggestions would be welcome.

**Comment by benjeffery** [comment]
@JereKoskela You haven't broken anything. tskit 0.3.0 has just been released, and has broken some of the (very corner case) tests here. I'll put in a PR to pin the dependency and you can rebase off that.

**Comment by JereKoskela** [comment]
> @JereKoskela You haven't broken anything. tskit 0.3.0 has just been released, and has broken some of the (very corner case) tests here. I'll put in a PR to pin the dependency and you can rebase off that.

That's a relief, thanks @benjeffery!

**Comment by benjeffery** [comment]
Actually we have # 1114 to fix this. We are waiting for conda to get the new release, then #1114 will be merged, then you can rebase!

**Comment by jeromekelleher** [comment]
Yep, apologies for the noise here! #1114 will be merged as soon as we have some conda packages built and all should be good once again.

**Comment by jeromekelleher** [comment]
If you rebase this should all be working now @JereKoskela.

**Comment by JereKoskela** [comment]
Thanks @jeromekelleher and @benjeffery! Defeating CircleCI always feels triumphant!

**Comment by benjeffery** [comment]
Circle CI is the final boss of tskit-dev repos.

**Review by jeromekelleher — APPROVED** [review]
LGTM, thanks @JereKoskela.

**Comment by jeromekelleher** [comment]
@TPPSellinger, can you have a look over this please?

**Comment by TPPSellinger** [comment]
I read everything carefully. I didn't see any mistake and I think everything is clear. I have only one minor topic which I didn't really see in the text (I apologize if i over-read it or if the question is trivial). In msprime,  events time have to be given in generations and not scaled time. Does the fact that multiple merger models scale differently impact this ? ping @JereKoskela

**Comment by JereKoskela** [comment]
> In msprime, events time have to be given in generations and not scaled time. Does the fact that multiple merger models scale differently impact this ?

All multiple merger models have been implemented by rescaling the coalescence rate, so that time is still measured in generations in all cases. I tried to avoid mentioning the phrase "time scale" at all to avoid any confusion, and just talk about numbers of generations, but I see upon second reading that a few time scales have still slipped in. I'll rephrase those in terms of generations too, and push in one more commit before this gets merged.

**Comment by TPPSellinger** [comment]
Okay, that what I thought. Thanks for everything @JereKoskela .

**Comment by jeromekelleher** [comment]
Great, thanks @TPPSellinger and @JereKoskela. Can you ping me when you're happy to merge please @JereKoskela?

**Comment by JereKoskela** [comment]
I've removed all trace of time scaling from the docs. Happy to merge if you two are @jeromekelleher and @TPPSellinger.

**Comment by TPPSellinger** [comment]
I went through the section mentioning generations and branch length and I think it's much more clear now.

**Pull request merged**
