### PR TITLE
More docs refactoring

### PR DESCRIPTION
**Pull request by jeromekelleher**
Work in progress to get a framework for the new docs in place. Dropping lots of TODOs so that we can open issues to track and follow up with smaller PRs.

### CODE REVIEW

**Comment by AdminBot-tskit** [comment]
📖 Docs for this PR can be previewed [here](https://tskit-dev.github.io/msprime-docs/1258/)

**Comment by grahamgower** [comment]
Whoa, msprime has a mailiing list! Now there's a well-kept secret!

**Comment by grahamgower** [comment]
I wonder if the docs layout makes it really easy to miss the `index.html` page?

**Comment by jeromekelleher** [comment]
> Whoa, msprime has a mailiing list! Now there's a well-kept secret!

It's not used much - we've talked a fair bit about setting up tags on biostars instead, but we never get around to it.

> I wonder if the docs layout makes it really easy to miss the index.html page?

Yeah - I guess we can experiment with other formats now that we've broken free from rtd. Maybe something like [furo](https://github.com/pradyunsg/furo)? (I might try it out actually, give a bit of impetus to this docs refactor)

**Comment by jeromekelleher** [comment]
Hey @benjeffery - there seems to be an issue with the docs build here where the upstream version isn't updating. It looks like the action is all working fine, but the website doesn't reflect the changes I'm making. 

(No hurry, just FYI)

**Comment by benjeffery** [comment]
> Hey @benjeffery - there seems to be an issue with the docs build here where the upstream version isn't updating. It looks like the action is all working fine, but the website doesn't reflect the changes I'm making.

Should all be fixed now - I've re-run the action on this PR so it should be up to date.

**Comment by jeromekelleher** [comment]
I think this is ready for review/merging.

It's a big change, and there's clearly a lot left to do, so I'm not sure how much use review is. I guess if someone really hates the new layout then this is a chance to push back on it. Otherwise, I'd like to merge this ASAP and start filing some issues against the stuff that needs doing, and close-out the old docs issues that aren't relevant any more.

I've tried not to delete any content at this point, mainly just moving stuff around. I'm hoping to have a high-level discussion about the new docs layout and the improvements we can make at the community meeting on Wednesday.

**Comment by jeromekelleher** [comment]
OK, nobody has jumped in to express their sincere loathing of the news docs setup, so I'm going to merge.

**Comment by jeromekelleher** [comment]
@benjeffery any chance of a +1 here please to appease the automerge gods?

**Review by benjeffery — APPROVED** [review]
LGTM!

**Pull request merged**
