### PR TITLE
mspms: fix parsing negative growth rates.

### LINKED ISSUE #1642: mspms: cannot specify negative growth rates in exp form
```
$ mspms -V
mspms 1.0.0b1

$ mspms 2 1 -t 1.0 -G -1e-5
usage: mspms [-h] [--mutation-rate theta] [--trees] [--recombination rho num_loci] [--gene-conversion gc_recomb_ratio tract_length]
             [--hotspots HOTSPOTS [HOTSPOTS ...]] [--structure value [value ...]] [--migration-matrix-entry i j rate]
             [--migration-matrix entry [entry ...]] [--migration-rate-change t x] [--migration-matrix-entry-change time i j rate]
             [--migration-matrix-change entry [entry ...]] [--growth-rate alpha] [--population-growth-rate population_id alpha]
             [--population-size population_id size] [--growth-rate-change t alpha] [--population-growth-rate-change t population_id alpha]
             [--size-change t x] [--population-size-change t population_id x] [--population-split t i j]
             [--admixture t population_id proportion] [--random-seeds x1 x2 x3] [--precision PRECISION] [-V] [-f FILENAME]
             sample_size num_replicates
mspms: error: argument --growth-rate/-G: expected one argument

$ mspms 2 1 -t 1.0 -G "-1e-5"
usage: mspms [-h] [--mutation-rate theta] [--trees] [--recombination rho num_loci] [--gene-conversion gc_recomb_ratio tract_length]
             [--hotspots HOTSPOTS [HOTSPOTS ...]] [--structure value [value ...]] [--migration-matrix-entry i j rate]
             [--migration-matrix entry [entry ...]] [--migration-rate-change t x] [--migration-matrix-entry-change time i j rate]
             [--migration-matrix-change entry [entry ...]] [--growth-rate alpha] [--population-growth-rate population_id alpha]
             [--population-size population_id size] [--growth-rate-change t alpha] [--population-growth-rate-change t population_id alpha]
             [--size-change t x] [--population-size-change t population_id x] [--population-split t i j]
             [--admixture t population_id proportion] [--random-seeds x1 x2 x3] [--precision PRECISION] [-V] [-f FILENAME]
             sample_size num_replicates
mspms: error: argument --growth-rate/-G: expected one argument
```

This works fine though.
```
$ mspms 2 1 -t 1.0 -G -0.00005
/home/grg/.local/bin/mspms 2 1 -t 1.0 -G -0.00005
2042601607 494589378 1595775956

//
segsites: 0
```

Simiarly for the `-eG` option.
```
$ mspms 2 1 -t 1.0 -eG 1.0 -1e5
usage: mspms [-h] [--mutation-rate theta] [--trees] [--recombination rho num_loci] [--gene-conversion gc_recomb_ratio tract_length]
             [--hotspots HOTSPOTS [HOTSPOTS ...]] [--structure value [value ...]] [--migration-matrix-entry i j rate]
             [--migration-matrix entry [entry ...]] [--migration-rate-change t x] [--migration-matrix-entry-change time i j rate]
             [--migration-matrix-change entry [entry ...]] [--growth-rate alpha] [--population-growth-rate population_id alpha]
             [--population-size population_id size] [--growth-rate-change t alpha] [--population-growth-rate-change t population_id alpha]
             [--size-change t x] [--population-size-change t population_id x] [--population-split t i j]
             [--admixture t population_id proportion] [--random-seeds x1 x2 x3] [--precision PRECISION] [-V] [-f FILENAME]
             sample_size num_replicates
mspms: error: argument --growth-rate-change/-eG: expected 2 arguments

$ mspms 2 1 -t 1.0 -eG 1.0 0.000005
/home/grg/.local/bin/mspms 2 1 -t 1.0 -eG 1.0 0.000005
307849011 337028153 2026495668

//
segsites: 2
positions: 0.076 0.527
10
01
```

### PR DESCRIPTION
**Pull request by grahamgower**
Closes #1642.

---

Upstream issue: https://bugs.python.org/issue9334
Discussion and workarounds: https://stackoverflow.com/questions/9025204/python-argparse-issue-with-optional-arguments-which-are-negative-numbers

### CODE REVIEW

**Comment by jeromekelleher** [comment]
I'm nervous about unintended consequences on this. Given that 
```
$ python3 mspms_dev.py 2 1 -t 1.0 -G=-1e-5
```
and 
```
$ python3 mspms_dev.py 2 1 -t 1.0 -G' -1e-5'
```
both work as workarounds and 
```
$ python3 mspms_dev.py 2 1 -t 1.0 -G-0.00001
```
works as expected, and that no-one has complained about this, I think I'd be inclined to document the workarounds and leave it as is.

**Comment by grahamgower** [comment]
Hmm. I admit, its a pretty hacky solution. As far as I can tell, the only one that works reliably is turning the arg into a string with leading whitespace. Consider one of the options that takes multiple args, like `-eG`.

These don't work:
```
mspms 2 1 -t 1.0 -eG '1 -1e-5'
```
```
mspms 2 1 -t 1.0 -eG='1 -1e-5'
```

But this does:
```
mspms 2 1 -t 1.0 -eG 1 ' -1e-5'
```

And the latter is accepted by `ms` too, so that's probably the best recommendation.

**Comment by jeromekelleher** [comment]
I agree it's ugly @grahamgower, but it's a corner case that people can work around, and given that this parser is quite convoluted already I really don't want to risk adding some unexpected behaviour. To be honest, I think the best recommendation is probably to avoid scientific notation - few people actually write these command lines by hand anyway.

**Comment by grahamgower** [comment]
Ok, I've reverted the workaround and added warnings to the docs and CLI help output. Hopefully that should be discoverable by a person copy/pasting an ms command from elsewhere.

**Review by jeromekelleher — APPROVED** [review]
Great, thanks.

**Pull request merged**
