### PR TITLE
Likelihood docs update

### LINKED ISSUE #1411: Documentation: utilities/computing_likelihoods should mention most analysis tools are in tskit
When looking at the page or section on "computing_likelihoods" the reader should be advised up top that most analysis tools are *not* in msprime, but in tskit (and a prominent link given), as people might expect a section named this to be about analysis.

### LINKED ISSUE #1423: Update the computing likelihoods page
The current [computing likelihoods](https://tskit.dev/msprime/docs/latest/likelihoods.html) page needs a little work

1. A little bit of background as to what we're doing an why we'd want to do it.
1. Change the text to refer to sim_ancestry rather than simulate
2. Add a Quick Reference section
3. Give a little bit of explanation about why ``discrete_genome`` must be False
4. Give a little bit more explanation as to what's happening in the examples, and maybe do them one-by-one (or maybe make a dict like ``{rho: msprime.log_arg_likelihood(ts, recombination_rate=rho, Ne=1) for rho in [0, 0.1, 1, 10]}``) rather than just doing a few prints. We could even consider plotting these values on a graph, or something?

Basically, it's a bit terse and technical at the moment and could do with a little more explanation. Basically, the docstrings are for terse, precise technical information and the explanation sections are for illustrating how things work to users at all levels.

See also #1411.

@JereKoskela, you're best positioned to pick this one up; any chance you could fit it in? The new [documentation docs](https://tskit.dev/msprime/docs/latest/development.html#documentation) should help orient you with the new way things are done.

### PR DESCRIPTION
**Pull request by JereKoskela**
I've added some background and description to the Computing likelihoods docs page. I have kept the examples as just print statements of likelihood values, with the intention that the surrounding descriptions will help interpret them. I don't think that e.g. a plot with 3-4 fairly arbitrary points with no obvious pattern would do the job better, though I'm happy to be outvoted.

Closes #1423
Closes #1411

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM!

**Comment by JereKoskela** [comment]
Thanks @jeromekelleher. I don't quite understand what's going on with the failing CLI test. Would you mind taking a quick look to see if it makes sense to you?

**Comment by jeromekelleher** [comment]
> Thanks @jeromekelleher. I don't quite understand what's going on with the failing CLI test. Would you mind taking a quick look to see if it makes sense to you?

It's a flakey test we've been having some issues with recently. I'll rerun.

**Comment by hyanwong** [comment]
Is there an easy way to view the generated docs from this PR (i.e. as an html page), or do I need to check out the PR myself and run `make` in the docs dir?

**Comment by hyanwong** [comment]
Only just got round to this, sorry. The :::warning syntax doesn't seem to work for me:

Screenshot 2021-02-04 at 11 15 38

**Comment by JereKoskela** [comment]
That's odd. It looks fine on my machine. Do either of the two warnings in ancestry.md work for you @hyanwong? My syntax is a copy-paste of one of them, unless I've made a mistake and am now blind to it.

**Comment by jeromekelleher** [comment]
> Is there an easy way to view the generated docs from this PR (i.e. as an html page), or do I need to check out the PR myself and run make in the docs dir?

No, autobuilding the docs led to  a security issue and we decided it wasn't worth the effort of fixing it. I think the issue you're having is the same problem you talked about in Slack.

**Comment by hyanwong** [comment]
> That's odd. It looks fine on my machine. Do either of the two warnings in ancestry.md work for you @hyanwong? My syntax is a copy-paste of one of them, unless I've made a mistake and am now blind to it.

They are borked for me too. It's probably the issue that @jeromekelleher mentioned above, that I asked about in Slack. So it's probably just my install and can be ignored.

**Pull request merged**
