### PR TITLE
Change multiple sweeps example to use complete sweeps.

### PR DESCRIPTION
**Pull request by molpopgen**

### CODE REVIEW

**Comment by jeromekelleher** [comment]
LGTM, happy to merge after a squash.

@andrewkern, can you comment please on this?

**Comment by molpopgen** [comment]
Oops.  Epic rebase fail.  Move along please....

**Comment by molpopgen** [comment]
This is ready for @andrewkern  to take a peek at.

**Comment by jeromekelleher** [comment]
@andrewkern, bump

**Comment by molpopgen** [comment]
I think so, let's see what @andrewkern says.

**Comment by jeromekelleher** [comment]
@molpopgen, seems like a simple change and consistent with other examples we're giving?

**Comment by molpopgen** [comment]
Yeah, that's what I had in mind, IIRC.

**Comment by jeromekelleher** [comment]
@molpopgen would you like to make this change or would you like me to do it?

**Comment by molpopgen** [comment]
I can do it in about 10 days.  I'm buried teaching two classes through next week.

**Comment by molpopgen** [comment]
I can do it in about 10 days.  I'm buried teaching two classes through next week.

**Comment by jeromekelleher** [comment]
Updated - looks OK?

**Comment by molpopgen** [comment]
Ah, I see what the question was now!  Yes, the Ne being set like this is great, and the changes are good.

**Review by jeromekelleher — APPROVED** [review]

**Pull request merged**
