### PR TITLE
Emulate v0.x discrete genome simulations.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Should help to reduce breakage of old code.

### CODE REVIEW

**Comment by petrelharp** [comment]
So you're putting the `discrete_genome` flag back in to simulate, for the pre-alpha users?

**Comment by jeromekelleher** [comment]
> So you're putting the discrete_genome flag back in to simulate, for the pre-alpha users?

No, it's to support old code that made discrete genome simulations by using the trick of making a rate map in which the ``num_loci`` is equal to ``sequence_length``.

**Comment by petrelharp** [comment]
oh! that makes more sense.

**Comment by jeromekelleher** [comment]
@mergifyio rebase

**Pull request merged**
