### PR TITLE
Fix codecov with token

### PR DESCRIPTION
**Pull request by benjeffery**
Last fix didn't push coverage successfully.

### CODE REVIEW

**Comment by benjeffery** [comment]
This is very odd - if I hard code the value of the codecov token this all works - put it in an environment variable and it all fails!

**Comment by benjeffery** [comment]
Solution was a checkbox buried in the circle CI config to allow secret sharing with PRs on forks.

**Comment by petrelharp** [comment]
which github emoji means facepalm?

**Comment by petrelharp** [comment]
also, thanks for figuring that out!

**Pull request merged**
