### PR TITLE
put back provenance in from_ts

### LINKED ISSUE #924: simulate with `from_ts` removes previous provenance entries
This bug was introduced in c2bf47a2ac59f9b8281647e63d4a8414786d4431. MWE:
```
ts = msprime.simulate(10, end_time=0.2)
rts = msprime.simulate(from_ts=ts)
print("Has ", rts.num_provenances, "provenances")
```
This prints `Has  1 provenances`, but should print `Has  2 provenances`.

### PR DESCRIPTION
**Pull request by petrelharp**
This fixes #924... but may well mess up some other stuff.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
LGTM, what do you think @benjeffery? Maintaining compatability with existing code and workflows is the most important thing. Also, in retrospect, I agree that keeping the provenance entries as a record of how the tree sequence was created is the right thing to do. I should have spotted this at the time, my bad.

**Comment by jeromekelleher** [comment]
On the grounds that this fixes a known bug, I say we merge this and follow up elsewhere to think about the provenance on from_ts.

@petrelharp, can you do a quick rebasearoo please?

**Comment by petrelharp** [comment]
`git rebasearoo`-'ed

**Comment by petrelharp** [comment]
Thanks!

**Pull request merged**
