### PR TITLE
Trigger docs site build if docs work

### PR DESCRIPTION
**Pull request by benjeffery**
Once a PR is merged the doc build will be triggered - putting the docs at https://tskit.dev/msprime/docs

Only the latest docs are currently shown.

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM!

**Comment by jeromekelleher** [comment]
Need a rebase here @benjeffery

**Comment by benjeffery** [comment]
I don't understand when or how, but this commit is already on `main` https://github.com/tskit-dev/msprime/commit/dc4bee841934aaddddc252633b8bbd993c7b35bf with a merge commit authored by you?!?!!!???!?!??!??!

**Comment by jeromekelleher** [comment]
Weird - github was doing funny things earlier :shrug:

**Pull request closed without merging**
