### PR TITLE
Docs structural updates

### PR DESCRIPTION
**Pull request by jeromekelleher**
- Add initial quickstart section.
- Change the titles for ancestry etc
- Move the API section to the bottom of the respective pages
- Change the order of sections

These are not polished final docs, just progress towards better docs based on feedback on the call last week.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
@agladstein - how does this quickstart look to you? It's not finished by any means, but should at least give some idea how the new APIs work.

**Comment by AdminBot-tskit** [comment]
📖 Docs for this PR can be previewed [here](https://tskit-dev.github.io/msprime-docs/PR-1294/)

**Comment by agladstein** [comment]
That's a good start. I'd say go ahead and merge that and we can work on it more.

**Comment by petrelharp** [comment]
Not sure if maybe Mutations should come after Demography?

**Comment by jeromekelleher** [comment]
> Not sure if maybe Mutations should come after Demography?

Hard to know - we can fine tune this later anyway.

**Comment by jeromekelleher** [comment]
@benjeffery - can I get an approval here please to appease mergify?

**Review by benjeffery — APPROVED** [review]

**Pull request merged**
