### PR TITLE
Refactoring verification.py

### PR DESCRIPTION
**Pull request by saunack**
Moved all the add_<instance_type>_instance() functions to a list containing a list of [<instance_type>, key, cmd]. To add another test, one needs to simply add the test into the list.

For grouping, I added another argument to the parser (--test) which takes in coma separated values. The can either match with <instance_type> or the first part of the key (eg msdoc, discoal in add_ms_instance etc). For other tests, I've put in custom tags like 'xidirac' or 'dtwf' based on comments already present in the code.
Not sure if this was the right way to go, but it's a start.

Also, changed all os.makedir calls to use the pre-existing make_test_dir().

### CODE REVIEW

**Comment by jeromekelleher** [comment]
This is good progress @saunack, and a big improvement over what we have right now. I think we should merge after the formatting problems have been fixed, and the problematic GC tests are skipped (like in upstream/master).

**Comment by jeromekelleher** [comment]
You need to rebase this off upstream/master @saunack - it's quite a long way behind the tip of master. This [guide](https://stdpopsim.readthedocs.io/en/latest/development.html#rebasing) might help.

**Comment by jeromekelleher** [comment]
Looks good @saunack. One last think, can you [squash](https://stdpopsim.readthedocs.io/en/latest/development.html#rebasing) the commits into one please? I'll merge then.

**Comment by jeromekelleher** [comment]
I've just merged another PR @saunack in #1028. I forgot that it touches verification.py, sorry, so that's introduced a conflict. Sorry.

Can you ``git fetch upstream/master`` and rebase again please?

**Comment by saunack** [comment]
Can you wait for a bit before merging? I think I found a small issue which I need to correct

**Comment by jeromekelleher** [comment]
OK, looks like the the rebase isn't quite right, see: https://github.com/tskit-dev/msprime/network

The base branch must be the tip of master - so,
```
git fetch upstream
git rebase -i upstream master
```
And you should just have one commit that'll go through cleanly. Can you try this please?

**Comment by jeromekelleher** [comment]
I'm happy to step in and fix it up @saunack, btw. Just let me know.

**Comment by saunack** [comment]
Looks like I'll need a bit of your help in this, unufortunately.

**Comment by jeromekelleher** [comment]
I think I see the problem you were hitting @saunack - you were rebasing against ``origin/master`` not ``upstream/master``. Please see the [github workflow](https://tskit.readthedocs.io/en/latest/development.html#workflow) here for the recommended way of working. On a busy project like this it's important to keep your upstream/master up to date and to rebase regularly while developing.

**Comment by saunack** [comment]
I did set the upstream branch and rebase against it. Might have been missing a step somewhere.
I'll take care to manage my workflow next time.

**Pull request merged**
