### PR TITLE
Add meson and ninja to developer requirements.

### PR DESCRIPTION
**Pull request by grahamgower**
See #1485.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Didn't realise there was a pip distribution of ninja, that's pretty handy. I don't think there's any harm in putting these in the dev requirements - @benjeffery, what do you think?

**Comment by benjeffery** [comment]
> Didn't realise there was a pip distribution of ninja, that's pretty handy. I don't think there's any harm in putting these in the dev requirements - @benjeffery, what do you think?

Meson doesn't have wheels and is built on `pip install` - does this cause issues for OSX/WIN?

**Comment by jeromekelleher** [comment]
It's pure python AFAIK, so doesn't matter?

**Review by benjeffery — APPROVED** [review]
Yep, looks like it is. All good!

**Comment by jeromekelleher** [comment]
Should probably add these to tskit dev requirements too so

**Pull request merged**
