### PR TITLE
Beta coalescent timescale typo correction

### PR DESCRIPTION
**Pull request by JereKoskela**
@TPPSellinger spotted an error in the Beta coalescent docstring, which is corrected here.

### CODE REVIEW

**Comment by eldonb** [comment]
two things:
1)  a good reference for  the diploid Schweinsberg model is the paper by  Birkner, Liu, Sturm in EJP:
https://projecteuclid.org/euclid.ejp/1527818427
maybe it could be referenced alongside the Blath et al (2013) paper in ancestry.py

2)  m(alpha) := E[X_1] =  1 +  (2^{1 - alpha}) / (alpha - 1)  is the correct formulation  in the  haploid case;
in ancestry.py it seems to be  1 +  2^{alpha - 1} / (alpha - 1)

**Comment by JereKoskela** [comment]
>     1. a good reference for  the diploid Schweinsberg model is the paper by  Birkner, Liu, Sturm in EJP:
>        https://projecteuclid.org/euclid.ejp/1527818427
>        maybe it could be referenced alongside the Blath et al (2013) paper in ancestry.py

Good point, thanks @eldonb! I'll add that into this PR.

>     2. m(alpha) := E[X_1] =  1 +  (2^{1 - alpha}) / (alpha - 1)  is the correct formulation  in the  haploid case;
>        in ancestry.py it seems to be  1 +  2^{alpha - 1} / (alpha - 1)

It's 1 + \\frac{1}{2^{\\alpha - 1} (\\alpha - 1)}, which matches what it should be. I put the 2 into the denominator because I kept getting confused about the sign of 1 - \alpha.

**Review by jeromekelleher — APPROVED** [review]

**Comment by jeromekelleher** [comment]
LGTM @JereKoskela - looks like this is ready to merge?

**Comment by JereKoskela** [comment]
> LGTM @JereKoskela - looks like this is ready to merge?

Yes, good to go @jeromekelleher

**Comment by TPPSellinger** [comment]
Quick question on line 1513. Why is N still divided by 2 although ploidy=1 ?

**Pull request merged**
