### PR TITLE
Quick hack to add single RE and breakpoints

### PR DESCRIPTION
**Pull request by jeromekelleher**
This adds single recombination nodes and storing of breakpoints to metadata in the algorithms.py script. Completely untested, just an easy way to get some input for other discussions (but I think we should do something like then when updating the real code).

@hyanwong, when you run something like this:
```
python3 algorithms.py 5 -L 100 -d -r 0.01 tmp.trees --full-arg
```
we get 
```
$ tskit nodes tmp.trees
id      is_sample       time    population      individual      metadata
0       1       0.000000        0       -1      {}
1       1       0.000000        0       -1      {}
2       1       0.000000        0       -1      {}
3       1       0.000000        0       -1      {}
4       1       0.000000        0       -1      {}
5       0       0.029150        0       -1      {'breakpoint': 82}
6       0       0.051952        0       -1      {}
7       0       0.129681        0       -1      {}
8       0       0.139396        0       -1      {'breakpoint': 13}
9       0       0.139502        0       -1      {}
10      0       0.161148        0       -1      {}
11      0       0.165444        0       -1      {}
12      0       0.405434        0       -1      {}
```
(annoyingly we put in ``is_sample`` here rather than ``flags`` - but note the ``breakpoint`` in the metadata)
and 
```
$ tskit edges tmp.trees
left    right   parent  child   metadata
0.000000        100.000000      5       1
0.000000        100.000000      6       3
0.000000        100.000000      6       4
0.000000        100.000000      7       0
0.000000        100.000000      7       6
0.000000        100.000000      8       2
82.000000       100.000000      9       5
0.000000        100.000000      9       7
0.000000        82.000000       10      5
13.000000       100.000000      10      8
0.000000        13.000000       11      8
0.000000        100.000000      11      10
0.000000        100.000000      12      9
0.000000        100.000000      12      11
```

This will make it easier to go back and forth between Griffiths ARGs and our edge annotated version.

@JereKoskela does the basic change of just dropping one "add_node" look right to you?

### CODE REVIEW

**Comment by JereKoskela** [comment]
Dropping one "add_node" is exactly what I've done in the C code in my local repo. I'm hoping to PR it some time next week - the likelihood function get a lot fiddlier as a result and needs some more tiem to get working again.

**Comment by jeromekelleher** [comment]
> the likelihood function get a lot fiddlier as a result and needs some more tiem to get working again.

Dammit - there was always going to be a drawback!

**Comment by hyanwong** [comment]
> Dropping one "add_node" is exactly what I've done in the C code in my local repo. I'm hoping to PR it some time next week - the likelihood function get a lot fiddlier as a result and needs some more tiem to get working again.

Oh, that's a pain! Sorry to hear that. I'd be interested to know why, over coffee some time. Thanks for doing it, though. I think this should make it a lot easier for others to work with our ARGs

**Comment by JereKoskela** [comment]
> > Dropping one "add_node" is exactly what I've done in the C code in my local repo. I'm hoping to PR it some time next week - the likelihood function get a lot fiddlier as a result and needs some more tiem to get working again.
> 
> Oh, that's a pain! Sorry to hear that. I'd be interested to know why, over coffee some time. Thanks for doing it, though. I think this should make it a lot easier for others to work with our ARGs

I'd be happy to elaborate over coffee whenever the chance arises, but essentially it's because finding all edges with a given node as either a child or a parent isn't straightforward. 

Suppose you're looking at a node whose parent is a recombination node. In order to work out the length of the non-ancestral material in which the recombination happens (which may be zero), you have to find the edges which go from the parent to the two grandparents and check their ancestral segments. That results in a fair bit more scrolling back and forth through the edge table than when everything was readable from a node and its two recombinant parents.

The extra complication isn't totally unexpected, and I think a single recombinant node is still the better way to do things. Hopefully there will e.g. be a non-trivial memory saving in full-args.

**Comment by jeromekelleher** [comment]
Could we add some metadata to make this easier @JereKoskela? I'm currently looking at adding the breakpoint anyway, would saving more information about the event help?

**Comment by JereKoskela** [comment]
> Could we add some metadata to make this easier @JereKoskela? I'm currently looking at adding the breakpoint anyway, would saving more information about the event help?

Storing the closest points of ancestral material to the left and to the right of the breakpoint would make things simpler again. That said, I'm pretty much done with this, so probably not worth doing unless there's a more general motivation for it.

**Comment by JereKoskela** [comment]
Trying to get the likelihood tests to pass has reminded me of what exactly the issue was with single-node recombination storing.

Suppose you have a lineage with a segment of trapped non-ancestral material, and that it forms a diamond. It will be impossible to recover the breakpoint from the nodes and edges, and therefore impossible to determine whether or not the trapped segment should be regarded as "extant" links for the purpose of working out a rate of effective recombinations in the likelihood calculation.

Fortunately, #1979 is exactly what we need to fix this, but it means the metadata update and fixing the likelihood need to be done concurrently.

@jeromekelleher, what do you think is the best way forward? Should I PR the update for the data structure (with a broken likelihood function) so that you can fix the metadata, or is there a better way?

**Pull request closed without merging**
