### PR TITLE
Added parse_fam function and tests from tskit

### PR DESCRIPTION
**Pull request by nikbaya**

### CODE REVIEW

**Comment by nikbaya** [comment]
@jeromekelleher is this what you had in mind?

**Comment by jeromekelleher** [comment]
The best approach is to rebase against upstream/main @nikbaya - the instructions [here](https://stdpopsim.readthedocs.io/en/stable/development.html#rebasing) should help

**Comment by nikbaya** [comment]
When I try `git rebase -i upstream/main` I can't get the merge commit that I made on the web UI to resolve differences with the main branch.

**Comment by nikbaya** [comment]
@jeromekelleher Could I just create a new branch and make my changes again? Seems like the simplest solution for me.

**Comment by benjeffery** [comment]
You can do that, and then force push to this branch to avoid making a new PR.

**Comment by jeromekelleher** [comment]
Or just make a new PR if you prefer @nikbaya - but it's probably worth figuring out how to rebase, it's a really really useful tool.

**Pull request merged**
