### PR TITLE
added nose to developer reqs

### PR DESCRIPTION
**Pull request by andrewkern**
i had to nuke my conda environment for tskit development and in recreating it i got tripped up by not having `nose`. i've added it to `requirements/development.txt` here

### CODE REVIEW

**Comment by petrelharp** [comment]
I thought we weren't using `nose` any more - just pytest?

**Comment by jeromekelleher** [comment]
Yep, it's all pytest now @andrewkern, we moved from nose a while back.

**Comment by andrewkern** [comment]
crap! is there new developer docs somewhere then? these still point to nose https://msprime.readthedocs.io/en/latest/development.html

**Comment by benjeffery** [comment]
https://tskit.dev/msprime/docs/latest/development.html

We need to put a redirect on readthedocs. It's been out of date for a while as the build broke there.

**Comment by benjeffery** [comment]
@andrewkern also in addition there is a good guide to purest command line options at https://tskit.dev/tskit/docs/latest/development.html#python-library

**Comment by andrewkern** [comment]
i can put a new link in the out of date msprime docs if that helps

**Comment by jeromekelleher** [comment]
We just need to do a redirect at some point - but we don't want to start sending people to tskit.dev *quite* yet, so I think it's best to live with this out-of-dateness for now.

**Pull request closed without merging**
