### PR TITLE
had to update some sweep verification for new API

### LINKED ISSUE #1577: Sojourn time tests broken
The analytical tests for sweeps are currently broken. Here's what we get:

sojourn

sojourn

Probably something got munged through the various API updates.

@andrewkern can you have a look please?

### PR DESCRIPTION
**Pull request by andrewkern**
closes #1577

### CODE REVIEW

**Comment by andrewkern** [comment]
huh it doesn't look like my edits are breaking this test... not sure what's going on after a quick scan

**Comment by jeromekelleher** [comment]
@mergifyio rebase

**Comment by jeromekelleher** [comment]
sojourn
sojourn

Looks like they're both a little bit off at the upper end @andrewkern - nothing to worry about?

**Comment by andrewkern** [comment]
yeah nothing to worry about-- this is the mathematical approximation breaking down i reckon

**Pull request merged**
