### PR TITLE
Tskit lib update

### PR DESCRIPTION
**Pull request by jeromekelleher**

### CODE REVIEW

**Comment by AdminBot-tskit** [comment]
📖 Docs for this PR can be previewed [here](https://tskit-dev.github.io/msprime-docs/PR-1319/)

**Review by benjeffery — APPROVED** [review]
LGTM, as long as the new clear doesn't imply any other changes due to retained provenance and schemas.

**Comment by jeromekelleher** [comment]
That's all very low-level stuff in the test suite @benjeffery, so we don't need to worry about metadata I think.

**Comment by jeromekelleher** [comment]
I didn't get the dependencies right on the initial go and I need to nuke the conda cache - what's the way to do this @benjeffery?

**Comment by benjeffery** [comment]
Increment the version in the cache key. Line 57 (currently "v9").

**Comment by jeromekelleher** [comment]
Merging manually as updates github actions.

**Pull request merged**
