### PR TITLE
Initial demes support (some updates)

### PR DESCRIPTION
**Pull request by apragsdale**
This takes this PR #1656 and adds some functionality and tests. It also addresses #1657 so that inactive populations are activated when they are ancestral populations in an admixture event.

Sorry for the duplicate @jeromekelleher ... wasn't able to figure out how to add and push to your PR, so copied it to work on it further.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Thanks @apragsdale - I'll take a look at this when I get a chance. Hopefully tomorrow?

**Comment by jeromekelleher** [comment]
I think this is basically ready to go. We could probably do with a bit more testing, but let's merge this much and try it out.

@grahamgower, how does it look to you?

Thanks very much for the updates @apragsdale, this was hugely helpful!

**Review by grahamgower — APPROVED** [review]
Looks good!

**Comment by jeromekelleher** [comment]
OK, let's merge after @apragsdale has had a chance to take a look.

**Comment by apragsdale** [comment]
I'm happy with it! Like you mentioned Jerome, testing is a bit light and it makes me worry that there could be some corner cases we are missing. Nothing obvious jumps out at me though

**Pull request merged**
