### PR TITLE
Use LightweightTableCollection code from tskit

### PR DESCRIPTION
**Pull request by jeromekelleher**
Initial pass at implementing the ideas in https://github.com/tskit-dev/tskit/pull/862

Tests pass fine locally.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
OK, looks like the basic idea of making a header file and including it in the target Python-C module works fine across the different platforms. There are some distribution headaches that I'll address with some upstream changes.

**Comment by jeromekelleher** [comment]
Huh, wasn't expecting that to work! How did git know about my remote? I'll never understand git submodules.

**Comment by AdminBot-tskit** [comment]
📖 Docs for this PR can be previewed [here](https://tskit-dev.github.io/msprime-docs/1215/)

**Comment by jeromekelleher** [comment]
I've updated this to use today's version of tskit. Normally we'd only pull in submodules at release tags, but it'd be good to get some experience of how the lwt code works in a subproject before we finalise things. I'll file an issue reminding us to update the tskit C module before we release.

How does it look to you @benjeffery?

**Comment by benjeffery** [comment]
> I've updated this to use today's version of tskit. Normally we'd only pull in submodules at release tags, but it'd be good to get some experience of how the lwt code works in a subproject before we finalise things. I'll file an issue reminding us to update the tskit C module before we release.
> 
> How does it look to you @benjeffery?

Looks good! Loving all the deleted code. Happy with having a non-tagged tskit as long as we fix before release!

**Comment by jeromekelleher** [comment]
Lodged issue to track tskit C API in #1256. I think this should be ready to go now.

**Review by benjeffery — APPROVED** [review]
I think the wheel building will be uneffected - we'll see after merging when the action runs.

**Pull request merged**
