### PR TITLE
Try executing gsl-config in shell

### PR DESCRIPTION
**Pull request by hyanwong**
Fixes #803 (hopefully)

### CODE REVIEW

**Comment by hyanwong** [comment]
Doesn't work yet, disappointingly.

**Comment by jeromekelleher** [comment]
Does running gsl-config on windows produce anything useful? (Can you check please @marianne-aspbury?)

**Comment by marianne-aspbury** [comment]
Not really, we can't get it to run. Have tried various ways of trying to interpret it as a bash script but ultimately windows complains: 
`
'gsl-config' is not recognized as an internal or external command,
operable program or batch file.
`
It definitely finds it, just can't open it. e.g. specifying `shell=True` in `subprocess.call()` just opens the file in a text editor. Otherwise it just complains the above.

**Comment by jeromekelleher** [comment]
OK, thanks. I wouldn't waste time with it, I don't think it's written to run on windows. It's in config.py as a "on the rate ocasions this works it's useful, but we can't rely on it".

**Comment by hyanwong** [comment]
It would obviously be neater to be able to run `gsl-config` on windows (it works fine on OS X). There must be a way. I'm just investigating.

**Pull request closed without merging**
