### PR TITLE
Add msp mutate CLI command. Closes #1075

### LINKED ISSUE #1075: Feature request: add_mutations command for msp
I would like to throw down N mutations randomly on a tree sequence. Is there a way I can currently do that with the tskit or msp CLI?

### PR DESCRIPTION
**Pull request by winni2k**
This adds the `mutate` verb to the `msp` CLI as proposed in #1075

### CODE REVIEW

**Comment by winni2k** [comment]
@jeromekelleher I think this PR is ready to be reviewed.

**Comment by jeromekelleher** [comment]
@petrelharp, what do you think of this CLI for ``mutate``?

**Comment by jeromekelleher** [comment]
OK,  merging then! Thanks Winni!

**Comment by winni2k** [comment]
Excellent! Thanks for the speedy review.

**Pull request merged**
