### PR TITLE
Update appveyor configutation.

### PR DESCRIPTION
**Pull request by jeromekelleher**

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks like we have a problem with GSL, possibly caused by an recent build update. Reported upstream: https://github.com/conda-forge/gsl-feedstock/issues/49

**Comment by jeromekelleher** [comment]
This is very strange. Looks like there's nothing in the include paths for GSL, even when I pin to something older.

**Comment by jeromekelleher** [comment]
Given your success with fixing gnarly CI issues @hyanwong, fancy taking a look at this?! It looks to me like the upstream GSL packages are broken, but it's very hard to pin it down without a windows machine. See the link above for the conda-forge issue I opened.

**Comment by hyanwong** [comment]
Running on Maz's laptop, it looks like windows can't execute `gsl-config` (which is a bash script, installed into `Library/bin/` within the anaconda msprime environment) - it might be that it needs to execute it using `bash.exe`?

**Comment by jeromekelleher** [comment]
> Running on Maz's laptop, it looks like windows simply can't execute gsl-config (which is a bash script, installed into Library/bin/ within the anaconda msprime environment) - it might be that it needs to execute it using bash.exe?

Running gsl-config has basically never worked on anything except Debian, so that's not what's changed I think.

**Comment by hyanwong** [comment]
Ah, OK. I might have been misled by the fact it works on my OS X laptop.

**Comment by hyanwong** [comment]
so apparently the `gsl_version.h` files are installed in `Library/include/gsl/...` on a fresh windows install. I don't know why the compiler can't find them. Here's a snippet of what you get when doing `dir` on the Appveyor system:

```
 Directory of C:\Miniconda36-x64\Library\include\gsl
...
71109/03/2019  05:31 PM               458 gsl_version.h
...
```

**Comment by hyanwong** [comment]
So it seems like this, at the top of setup.py:

```
os.getenv("MSP_CONDA_PREFIX", None)
```

is returning `None` on windows systems. Is that expected?

**Comment by jeromekelleher** [comment]
Umm, I'm not sure. I don't think this has been used in Windows for a long time (if it ever was). Presumably this is being used in the Travis config?

**Comment by hyanwong** [comment]
OK - I think this is the problem: the compiler is running the following command:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo
 /Ox /W3 /GL /DNDEBUG /MD -DGSL_DLL -DWIN32 -UNDEBUG -Ilib
 -Ilib\subprojects\tskit -Ilib\subprojects\tskit\tskit -Ilib\subprojects\kastore
 -IC:\\Miniconda37-x64\Library\include
 -IC:\Miniconda37-x64\envs\testenv\include
 -IC:\Miniconda37-x64\envs\testenv\include
 -IC:\Miniconda37-x64\envs\testenv\lib\site-packages\numpy\core\include 
 "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE"
 "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE"
 "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt"
 "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um"
 "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared"
 "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um"
 "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt"
 /Tc_msprimemodule.c /Fobuild\temp.win-amd64-3.7\Release\_msprimemodule.obj -std=c99
```

but the gsl headers (`gsl/gsl_xxx.h`) are (apparently) in 

```
C:\Miniconda37-x64\envs\testenv\Library\include
```

which isn't in the include paths for the compiler

**Comment by hyanwong** [comment]
> Umm, I'm not sure. I don't think this has been used in Windows for a long time (if it ever was). Presumably this is being used in the Travis config?

I'm pretty sure it was defined in the previous appveyor.yml file ( it was removed in the breaking PR), and `setup.py` has some windows-specific paths that seem to use it. But I don't know how to get the path to `testenv` within the setup.py file, otherwise I could simply fix it.

**Comment by hyanwong** [comment]
This PR is now obsoleted by #814 and can be closed

**Pull request closed without merging**
