### PR TITLE
changing this doc string

### PR DESCRIPTION
**Pull request by andrewkern**
editing the warning introduced in #1955 for clarity as to what the issue is

### CODE REVIEW

**Comment by petrelharp** [comment]
I'm confused - what *does* it mean if you run it back to a high initial frequency, if not a "sweep from standing genetic variation"?

**Comment by andrewkern** [comment]
that you aren't conditioning on allele frequency dynamics back in time, past when the allele hit the final frequency

**Comment by molpopgen** [comment]
> I'm confused - what _does_ it mean if you run it back to a high initial frequency, if not a "sweep from standing genetic variation"?

It means that you've taken a structured coalescent back to some point determined by "initial frequency" and then suddenly unstructure it (b/c there's no merged API that means "finish it w/a neutral trajectory").

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Pull request merged**
