### PR TITLE
coalescence rate calculation fix

### PR DESCRIPTION
**Pull request by petrelharp**
Turns out we weren't calculating coalescence rate calculations correctly if there was more than one lineage movement at the same time. This fixes that and adds some tests.

### CODE REVIEW

**Comment by petrelharp** [comment]
Closes #1618

**Review by jeromekelleher — COMMENTED** [review]
LGTM. 

A nice additional test might be to test a few known values for the OOA model. Should be a quick test (`dbg = Demography._ooa_model().debug()`) and we've got the values lying around at the moment anyway.

**Comment by petrelharp** [comment]
Ok; added that test and squashed.

**Review by jeromekelleher — APPROVED** [review]

**Comment by jeromekelleher** [comment]
@mergifyio rebase

**Comment by jeromekelleher** [comment]
Hmm, looks like this is failing on Python 3.7. Need to specify the tolerances maybe?

**Comment by jeromekelleher** [comment]
Not sure why this is failing @petrelharp - can you rebase maybe? The PR is a bit behind the tip.

**Comment by petrelharp** [comment]
WTF, windows:
```
E        +  where False = <function allclose at 0x000001E2AF7ACB88>((0.5 / array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])), 7300, rtol=0.001)
```

**Comment by jeromekelleher** [comment]
Could skip-if windows, and file an issue? Looks like these numerics are tricky.

**Pull request merged**
