### PR TITLE
small docfix

### PR DESCRIPTION
**Pull request by petrelharp**
Previously this link was broken, I guess because of the linebreak. And, that is a 3-generatoin pedigree.

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]

**Comment by jeromekelleher** [comment]
Any idea what's going on with the missing kastore stuff in the circleCI failure @benjeffery? Mystery to me!

**Comment by benjeffery** [comment]
> Any idea what's going on with the missing kastore stuff in the circleCI failure @benjeffery? Mystery to me!

How bizarre. Looking into it.

**Comment by benjeffery** [comment]
Rebase once #2112 is merged and it should add work.

**Comment by benjeffery** [comment]
@mergyifyio rebase

**Comment by jeromekelleher** [comment]
@mergifyio rebase

**Comment by benjeffery** [comment]
@mergifyio rebase

**Comment by jeromekelleher** [comment]
Not sure what happened here, not worth digging in.

**Pull request merged**
