### PR TITLE
Fix OSX tests

### PR DESCRIPTION
**Pull request by benjeffery**

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]

**Comment by benjeffery** [comment]
No clue why kastore isn't found by conda.

**Comment by benjeffery** [comment]
The latest macosx image uses M1 silicon - which conda doesn't have a kastore build for, so using the old one.

**Review by jeromekelleher — APPROVED** [review]

**Comment by benjeffery** [comment]
@mergifyio rebase

**Comment by benjeffery** [comment]
Ahhh, this needs a mergify update

**Comment by benjeffery** [comment]
Manual merge to update mergify config.

**Pull request merged**
