### PR TITLE
Change end time inequality

### LINKED ISSUE #1304: Behavior of `end_time` when using "dtwf" model
I'm confused about the behavior of `end_time` when the model is set to "dtwf". When simulating using `sim_ancestry`, if I set the `end_time=1`, I figured the simulation would run for a single generation. I can see this in the "hudson" model, running `sim_ancestry` with `end_time=1` gives me multiple trees. However, simulating with "dtwf" and `end_time=1` results always in a single tree, so that nothing has occurred. Instead, specifying `end_time=2` with the "dtwf" model results in roughly the same distribution of the number of trees as with the "hudson" model and `end_time=1`.

Is this the intended behavior, or is the "dtwf" model ending a generation too early when `end_time` is specified?

Edit, as an illustration, with 2 samples, Ne=1000, a segment of 1 Morgan, with 20,000 replicates:
num_trees

### PR DESCRIPTION
**Pull request by apragsdale**
Closes #1304

Some tests are still failing here.. trying to figure out what's going on

### CODE REVIEW

**Comment by apragsdale** [comment]
I fiddled with tests a bit to get them to pass. There were a few testing the timing of some events when it equaled the set end time, of course, so would be good to check that I haven't made those tests useless.

Also, two tests were failing in lib/tests/ancestry.c, and I'm wondering if lines 373 and 489 should be changed to `ret = msp_run(&msp, 10.0-1e-6, ULONG_MAX);`..?

**Comment by jeromekelleher** [comment]
Excellent, thanks @apragsdale! Yes, I think you're right we can change those C tests. This does mean that our semantics wrt events like sampling etc is slightly different than before, I guess it's unlikely anyone is actually depending on this. This is the sort of stuff we want to break for 1.0 anyway, while we're breaking stuff.

We should add a note to the CHANGELOG to make sure we don't forget to tell people about it, though.l

**Comment by apragsdale** [comment]
Ok, changelog updated. Let me know if you want any changes made here, or if I should rebase/etc

**Comment by jeromekelleher** [comment]
Looks great, thanks @apragsdale. I think we just need to update the documentation for the ``end_time`` parameter, squash and we're good to merge.

**Comment by apragsdale** [comment]
Is this ok to merge? Not sure what to do about the one codecov failuer here.

**Comment by jeromekelleher** [comment]
@mergifyIO please rebase

**Comment by jeromekelleher** [comment]
@Mergifyio  rebase

**Comment by jeromekelleher** [comment]
@Mergifyio rebase

**Review by jeromekelleher — APPROVED** [review]
LGTM, thanks @apragsdale!

**Comment by apragsdale** [comment]
Thanks Jerome - glad to get this sorted!

**Comment by jeromekelleher** [comment]
Thanks for sorting it out @apragsdale!

**Pull request merged**
