### PR TITLE
Allow initial_size=0.

### LINKED ISSUE #1125: population sizes can't be zero, so positive sizes are used where they don't make sense
Consider a three population model, `(0, (1, 2))`, where `0` is the ancestor of `1` and `2`. Furthermore, we have that `0` goes extinct at some time `T`, and `1` and `2` pop into existance at this time.

The typical way of describing this model is as follows.
```python
import msprime

N = 1000
T = 500
population_configurations = [
    msprime.PopulationConfiguration(initial_size=N),
    msprime.PopulationConfiguration(initial_size=N),
    msprime.PopulationConfiguration(initial_size=N),
]
demographic_events = [
    msprime.MassMigration(T, source=1, dest=0),
    msprime.MassMigration(T, source=2, dest=0),
]

ddb = msprime.DemographyDebugger(
    population_configurations=population_configurations,
    demographic_events=demographic_events,
)
ddb.print_history()
```
Which results in the following output:
```
Model =  hudson(reference_size=1)
=============================
Epoch: 0 -- 500.0 generations
=============================
     start     end      growth_rate |     0        1        2
   -------- --------       -------- | -------- -------- --------
0 |  1e+03    1e+03               0 |     0        0        0
1 |  1e+03    1e+03               0 |     0        0        0
2 |  1e+03    1e+03               0 |     0        0        0

Events @ generation 500.0
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 1 & dest 0
                     (equivalent to migration from 0 to 1 forwards in time)
   - Mass migration: Lineages moved with probability 1.0 backwards in time with source 2 & dest 0
                     (equivalent to migration from 0 to 2 forwards in time)
===============================
Epoch: 500.0 -- inf generations
===============================
     start     end      growth_rate |     0        1        2
   -------- --------       -------- | -------- -------- --------
0 |  1e+03    1e+03               0 |     0        0        0
1 |  1e+03    1e+03               0 |     0        0        0
2 |  1e+03    1e+03               0 |     0        0        0
```

But I would argue that the population sizes should be zero outside the epochs where the populations exist. This would be a more accurate representation of the demograpy (but neither `PopulationConfiguration` nor `PopulationParametersChange` permit `initial_size=0`):
```
N = 1000
T = 500
population_configurations = [
    msprime.PopulationConfiguration(initial_size=0),
    msprime.PopulationConfiguration(initial_size=N),
    msprime.PopulationConfiguration(initial_size=N),
]
demographic_events = [
    msprime.PopulationParametersChange(T, initial_size=N, population_id=0),
    msprime.MassMigration(T, source=1, dest=0),
    msprime.MassMigration(T, source=2, dest=0),
    msprime.PopulationParametersChange(T, initial_size=0, population_id=1),
    msprime.PopulationParametersChange(T, initial_size=0, population_id=2),
]
```

A possible simpler alternative would be to have `PopulationConfiguration` and `PopulationParametersChange` accept an `enable` parameter that defaults to `True`?

### PR DESCRIPTION
**Pull request by grahamgower**
Closes #1125.

### CODE REVIEW

**Comment by grahamgower** [comment]
It seems that something more is needed. Sampling from a population with N=0 should fail, but doesn't in all cases. And sampling from an ancient population that had initial_size=0 in the population configuration, but population size increased at an older time, should be reasonable. In the latter case each sample is (erroneously) a singleton root!

**Comment by jeromekelleher** [comment]
We can check for population size = 0 when we add samples [here](https://github.com/tskit-dev/msprime/blob/master/lib/msprime.c#L3298). It should be a simple matter to check if ``population->initial_size == 0``, and that will catch all cases in which we try to sample from zero-size pops, as it's checking the initial_size at the appopriate time.

We'll want to get some simple C tests in for this as well @grahamgower - just to make sure we're covering these new code paths.

**Comment by grahamgower** [comment]
> We can check for population size = 0 when we add samples [here](https://github.com/tskit-dev/msprime/blob/master/lib/msprime.c#L3298). It should be a simple matter to check if `population->initial_size == 0`, and that will catch all cases in which we try to sample from zero-size pops, as it's checking the initial_size at the appopriate time.

Is there an easy way to find out the size of a population at a particular time (without running the simulation or the demography debugger)? Because for a model like in the tests I added here, the *time* of sampling dictates whether sampling should be permitted.

> We'll want to get some simple C tests in for this as well @grahamgower - just to make sure we're covering these new code paths.

Yep, can do.

Do you have any insight about why what's going on in this case where we attempt to sample from the ancestral population at an appropritate time point?
```python
import msprime

N = 1000
T = 500
population_configurations = [
    msprime.PopulationConfiguration(initial_size=0),
    msprime.PopulationConfiguration(initial_size=N),
    msprime.PopulationConfiguration(initial_size=N),
]
demographic_events = [
    msprime.MassMigration(T, source=1, dest=0),
    msprime.MassMigration(T, source=2, dest=0),
    msprime.PopulationParametersChange(T, initial_size=N, population_id=0),
    msprime.PopulationParametersChange(T, initial_size=0, population_id=1),
    msprime.PopulationParametersChange(T, initial_size=0, population_id=2),
]

ts = msprime.simulate(
    population_configurations=population_configurations,
    demographic_events=demographic_events,
    samples=[msprime.Sample(0, 2 * T)] * 10,
)

print(ts.first().draw(format="ascii"))
print("num_roots =", ts.first().num_roots)
```
Which with the current pr outputs the following:
```
0  1  2  3  4  5  6  7  8  9

num_roots = 10
```

**Comment by jeromekelleher** [comment]
> Is there an easy way to find out the size of a population at a particular time (without running the simulation or the demography debugger)? Because for a model like in the tests I added here, the time of sampling dictates whether sampling should be permitted.

No, we'll just have to catch that at run-time. That's fine.

**Comment by jeromekelleher** [comment]
> Do you have any insight about why what's going on in this case where we attempt to sample from the ancestral population at an appropritate time point?

Ah yes, that's #983

**Comment by jeromekelleher** [comment]
Is this ready for final review @grahamgower?

**Comment by grahamgower** [comment]
> Is this ready for final review @grahamgower?

Yep, sorry. I've squashed/rebased now.

**Review by jeromekelleher — APPROVED** [review]
Looks great, thanks @grahamgower!

**Pull request merged**
