### PR TITLE
Add initial verification tests for instantaneous_bottleneck

### PR DESCRIPTION
**Pull request by jeromekelleher**
Converted some of @KLohse notebook code to use in the verification suite.

Looks like we do have some problems, but probably due to #1458 

I would suggest we merge this much and try to get Konrad (or someone else??) to look at the verification outputs and puzzle out what's going on. Also, we should be clear what the ploidy of the model is.

### CODE REVIEW

**Review by GertjanBisschop — COMMENTED** [review]
Sorry about the wait. Double check the scaling on the strength of the bottleneck, but otherwise everything checks out. Will probably be the issue you mentioned.

**Comment by jeromekelleher** [comment]
OK @GertjanBisschop and @KLohse I think this is it: we can finally close #9! Can you take a quick look over this please? I've fixed the scaling issue and the analytical checks are bang on now.

**Comment by jeromekelleher** [comment]
I'm going to go ahead and merge this - we can follow up with some updates if anyone spots issues. Great to get this finished -FINALLY!

**Comment by GertjanBisschop** [comment]
Looks great. Great job on finally closing #9 and a factor of 2 error well-spotted in #1458.

**Pull request merged**
